using System;
using System.Linq;
using System.Runtime.InteropServices;
using Server.Items;
using System.Collections.Generic;

namespace Server.Misc
{
 		
        class ClasseInit 
        {
				public static void Configure()
				{
	
	
	//	public Classe(int ClasseID,	string name, int classLvl, int armor, bool hidden, List<int> evolution, 	Dictionary<SkillName, double> skill	)
	
			  	Classe.RegisterClasse(new Classe(0, "Aucune",0,0,false,false,new List<int>(){1,2,3,4,5}, new Dictionary<SkillName, double>() {  }));	
				Classe.RegisterClasse(new Classe(1, "Historien",0,0,true,false, new List<int>(){}, new Dictionary<SkillName, double>() { {SkillName.Cartography, 100}, {SkillName.Inscribe, 100}})); 
				Classe.RegisterClasse(new Classe(2, "Ingénieur",0,0,true,false, new List<int>(){}, new Dictionary<SkillName, double>() { {SkillName.Blacksmith, 100}, {SkillName.Tinkering, 100}})); 
				Classe.RegisterClasse(new Classe(3, "Styliste",0,0,true,false, new List<int>(){}, new Dictionary<SkillName, double>() { {SkillName.Carpentry, 100}, {SkillName.Tailoring, 100}})); 
				Classe.RegisterClasse(new Classe(4, "Épicier",0,0,true,false, new List<int>(){}, new Dictionary<SkillName, double>() { {SkillName.Cooking, 100}, {SkillName.Alchemy, 100}})); 
				Classe.RegisterClasse(new Classe(5, "Recrue",0,3,false,false, new List<int>(){6,7}, new Dictionary<SkillName, double>() { {SkillName.Anatomy, 50}, {SkillName.AnimalLore, 30}, {SkillName.Camping, 30}, {SkillName.Parry, 50}, {SkillName.Peacemaking, 30}, {SkillName.Discordance, 30}, {SkillName.EvalInt, 30}, {SkillName.Healing, 50}, {SkillName.Herding, 50}, {SkillName.Hiding, 30}, {SkillName.Provocation, 30}, {SkillName.Lockpicking, 30}, {SkillName.Magery, 30}, {SkillName.Equitation, 50}, {SkillName.Tactics, 50}, {SkillName.Snooping, 30}, {SkillName.Musicianship, 30}, {SkillName.Poisoning, 30}, {SkillName.Archery, 50}, {SkillName.Stealing, 30}, {SkillName.AnimalTaming, 30}, {SkillName.Tracking, 30}, {SkillName.Veterinary, 30}, {SkillName.Swords, 60}, {SkillName.Macing, 60}, {SkillName.Fencing, 60}, {SkillName.Wrestling, 60}, {SkillName.Meditation, 30}, {SkillName.Focus, 50}, }, new Dictionary<MagieType, int>() {})); 
				Classe.RegisterClasse(new Classe(6, "Chasseur",1,3,false,false, new List<int>(){18,19,20,21,22,23,24,25,26}, new Dictionary<SkillName, double>() { {SkillName.Anatomy, 85}, {SkillName.AnimalLore, 30}, {SkillName.Camping, 30}, {SkillName.Parry, 30}, {SkillName.Peacemaking, 30}, {SkillName.Discordance, 30}, {SkillName.EvalInt, 30}, {SkillName.Healing, 50}, {SkillName.Herding, 50}, {SkillName.Hiding, 30}, {SkillName.Provocation, 30}, {SkillName.Lockpicking, 30}, {SkillName.Magery, 30}, {SkillName.Equitation, 50}, {SkillName.Tactics, 85}, {SkillName.Snooping, 30}, {SkillName.Musicianship, 30}, {SkillName.Poisoning, 30}, {SkillName.Archery, 85}, {SkillName.Stealing, 30}, {SkillName.AnimalTaming, 30}, {SkillName.Tracking, 30}, {SkillName.Veterinary, 30}, {SkillName.Swords, 60}, {SkillName.Macing, 60}, {SkillName.Fencing, 60}, {SkillName.Wrestling, 60}, {SkillName.Meditation, 30}, {SkillName.Focus, 50}, }, new Dictionary<MagieType, int>() {})); 
				Classe.RegisterClasse(new Classe(7, "Combattant",1,4,false,false, new List<int>(){8,9,10,11,12,13,14,15,16,17}, new Dictionary<SkillName, double>() { {SkillName.Anatomy, 85}, {SkillName.AnimalLore, 30}, {SkillName.Camping, 30}, {SkillName.Parry, 60}, {SkillName.Peacemaking, 30}, {SkillName.Discordance, 30}, {SkillName.EvalInt, 30}, {SkillName.Healing, 60}, {SkillName.Herding, 50}, {SkillName.Hiding, 30}, {SkillName.Provocation, 30}, {SkillName.Lockpicking, 30}, {SkillName.Magery, 30}, {SkillName.Equitation, 50}, {SkillName.Tactics, 85}, {SkillName.Snooping, 30}, {SkillName.Musicianship, 30}, {SkillName.Poisoning, 30}, {SkillName.Archery, 50}, {SkillName.Stealing, 30}, {SkillName.AnimalTaming, 30}, {SkillName.Tracking, 30}, {SkillName.Veterinary, 30}, {SkillName.Swords, 85}, {SkillName.Macing, 85}, {SkillName.Fencing, 85}, {SkillName.Wrestling, 85}, {SkillName.Meditation, 30}, {SkillName.Focus, 50}, }, new Dictionary<MagieType, int>() {})); 
				Classe.RegisterClasse(new Classe(8, "Gardien",2,6,false,false, new List<int>(){}, new Dictionary<SkillName, double>() { {SkillName.Anatomy, 85}, {SkillName.AnimalLore, 30}, {SkillName.Camping, 30}, {SkillName.Parry, 100}, {SkillName.Peacemaking, 30}, {SkillName.Discordance, 30}, {SkillName.EvalInt, 30}, {SkillName.Healing, 60}, {SkillName.Herding, 100}, {SkillName.Hiding, 30}, {SkillName.Provocation, 30}, {SkillName.Lockpicking, 30}, {SkillName.Magery, 30}, {SkillName.Equitation, 50}, {SkillName.Tactics, 85}, {SkillName.Snooping, 30}, {SkillName.Musicianship, 30}, {SkillName.Poisoning, 30}, {SkillName.Archery, 50}, {SkillName.Stealing, 30}, {SkillName.AnimalTaming, 30}, {SkillName.Tracking, 30}, {SkillName.Veterinary, 30}, {SkillName.Swords, 100}, {SkillName.Macing, 100}, {SkillName.Fencing, 100}, {SkillName.Wrestling, 100}, {SkillName.Meditation, 30}, {SkillName.Focus, 50}, }, new Dictionary<MagieType, int>() {})); 
				Classe.RegisterClasse(new Classe(9, "Cavalier",2,5,false,false, new List<int>(){}, new Dictionary<SkillName, double>() { {SkillName.Anatomy, 85}, {SkillName.AnimalLore, 30}, {SkillName.Camping, 30}, {SkillName.Parry, 80}, {SkillName.Peacemaking, 30}, {SkillName.Discordance, 30}, {SkillName.EvalInt, 30}, {SkillName.Healing, 80}, {SkillName.Herding, 50}, {SkillName.Hiding, 30}, {SkillName.Provocation, 30}, {SkillName.Lockpicking, 30}, {SkillName.Magery, 30}, {SkillName.Equitation, 100}, {SkillName.Tactics, 85}, {SkillName.Snooping, 30}, {SkillName.Musicianship, 30}, {SkillName.Poisoning, 30}, {SkillName.Archery, 50}, {SkillName.Stealing, 30}, {SkillName.AnimalTaming, 30}, {SkillName.Tracking, 30}, {SkillName.Veterinary, 30}, {SkillName.Swords, 100}, {SkillName.Macing, 100}, {SkillName.Fencing, 100}, {SkillName.Wrestling, 100}, {SkillName.Meditation, 30}, {SkillName.Focus, 50}, }, new Dictionary<MagieType, int>() {})); 
				Classe.RegisterClasse(new Classe(10, "Hero",2,5,false,false, new List<int>(){}, new Dictionary<SkillName, double>() { {SkillName.Anatomy, 85}, {SkillName.AnimalLore, 30}, {SkillName.Camping, 30}, {SkillName.Parry, 85}, {SkillName.Peacemaking, 30}, {SkillName.Discordance, 30}, {SkillName.EvalInt, 30}, {SkillName.Healing, 60}, {SkillName.Herding, 50}, {SkillName.Hiding, 30}, {SkillName.Provocation, 30}, {SkillName.Lockpicking, 30}, {SkillName.Magery, 30}, {SkillName.Equitation, 50}, {SkillName.Tactics, 100}, {SkillName.Snooping, 30}, {SkillName.Musicianship, 30}, {SkillName.Poisoning, 30}, {SkillName.Archery, 50}, {SkillName.Stealing, 30}, {SkillName.AnimalTaming, 30}, {SkillName.Tracking, 30}, {SkillName.Veterinary, 30}, {SkillName.Swords, 100}, {SkillName.Macing, 100}, {SkillName.Fencing, 100}, {SkillName.Wrestling, 100}, {SkillName.Meditation, 30}, {SkillName.Focus, 100}, }, new Dictionary<MagieType, int>() {})); 
				Classe.RegisterClasse(new Classe(11, "Medecin de guerre",2,5,false,false, new List<int>(){}, new Dictionary<SkillName, double>() { {SkillName.Anatomy, 100}, {SkillName.AnimalLore, 30}, {SkillName.Camping, 75}, {SkillName.Parry, 85}, {SkillName.Peacemaking, 30}, {SkillName.Discordance, 30}, {SkillName.EvalInt, 30}, {SkillName.Healing, 100}, {SkillName.Herding, 60}, {SkillName.Hiding, 30}, {SkillName.Provocation, 30}, {SkillName.Lockpicking, 30}, {SkillName.Magery, 30}, {SkillName.Equitation, 50}, {SkillName.Tactics, 85}, {SkillName.Snooping, 30}, {SkillName.Musicianship, 30}, {SkillName.Poisoning, 30}, {SkillName.Archery, 50}, {SkillName.Stealing, 30}, {SkillName.AnimalTaming, 30}, {SkillName.Tracking, 30}, {SkillName.Veterinary, 30}, {SkillName.Swords, 100}, {SkillName.Macing, 100}, {SkillName.Fencing, 100}, {SkillName.Wrestling, 100}, {SkillName.Meditation, 30}, {SkillName.Focus, 50}, }, new Dictionary<MagieType, int>() {})); 
				Classe.RegisterClasse(new Classe(12, "Sergent Arcaniste",2,4,false,false, new List<int>(){}, new Dictionary<SkillName, double>() { {SkillName.Anatomy, 85}, {SkillName.AnimalLore, 30}, {SkillName.Camping, 30}, {SkillName.Parry, 80}, {SkillName.Peacemaking, 30}, {SkillName.Discordance, 30}, {SkillName.EvalInt, 30}, {SkillName.Healing, 60}, {SkillName.Herding, 50}, {SkillName.Hiding, 30}, {SkillName.Provocation, 30}, {SkillName.Lockpicking, 30}, {SkillName.Magery, 100}, {SkillName.Equitation, 50}, {SkillName.Tactics, 85}, {SkillName.Snooping, 30}, {SkillName.Musicianship, 30}, {SkillName.Poisoning, 30}, {SkillName.Archery, 50}, {SkillName.Stealing, 30}, {SkillName.AnimalTaming, 30}, {SkillName.Tracking, 30}, {SkillName.Veterinary, 30}, {SkillName.Swords, 100}, {SkillName.Macing, 100}, {SkillName.Fencing, 100}, {SkillName.Wrestling, 100}, {SkillName.Meditation, 30}, {SkillName.Focus, 50}, }, new Dictionary<MagieType, int>() {})); 
				Classe.RegisterClasse(new Classe(13, "Paladin",2,4,false,false, new List<int>(){}, new Dictionary<SkillName, double>() { {SkillName.Anatomy, 85}, {SkillName.AnimalLore, 30}, {SkillName.Camping, 30}, {SkillName.Parry, 80}, {SkillName.Peacemaking, 30}, {SkillName.Discordance, 30}, {SkillName.EvalInt, 30}, {SkillName.Healing, 60}, {SkillName.Herding, 50}, {SkillName.Hiding, 30}, {SkillName.Provocation, 30}, {SkillName.Lockpicking, 30}, {SkillName.Magery, 100}, {SkillName.Equitation, 50}, {SkillName.Tactics, 85}, {SkillName.Snooping, 30}, {SkillName.Musicianship, 30}, {SkillName.Poisoning, 30}, {SkillName.Archery, 50}, {SkillName.Stealing, 30}, {SkillName.AnimalTaming, 30}, {SkillName.Tracking, 30}, {SkillName.Veterinary, 30}, {SkillName.Swords, 100}, {SkillName.Macing, 100}, {SkillName.Fencing, 100}, {SkillName.Wrestling, 100}, {SkillName.Meditation, 30}, {SkillName.Focus, 50}, }, new Dictionary<MagieType, int>() {})); 
				Classe.RegisterClasse(new Classe(14, "Sombre Dueliste",2,4,false,false, new List<int>(){}, new Dictionary<SkillName, double>() { {SkillName.Anatomy, 85}, {SkillName.AnimalLore, 30}, {SkillName.Camping, 30}, {SkillName.Parry, 80}, {SkillName.Peacemaking, 30}, {SkillName.Discordance, 30}, {SkillName.EvalInt, 30}, {SkillName.Healing, 60}, {SkillName.Herding, 50}, {SkillName.Hiding, 30}, {SkillName.Provocation, 30}, {SkillName.Lockpicking, 30}, {SkillName.Magery, 100}, {SkillName.Equitation, 50}, {SkillName.Tactics, 85}, {SkillName.Snooping, 30}, {SkillName.Musicianship, 30}, {SkillName.Poisoning, 30}, {SkillName.Archery, 50}, {SkillName.Stealing, 30}, {SkillName.AnimalTaming, 30}, {SkillName.Tracking, 30}, {SkillName.Veterinary, 30}, {SkillName.Swords, 100}, {SkillName.Macing, 100}, {SkillName.Fencing, 100}, {SkillName.Wrestling, 100}, {SkillName.Meditation, 30}, {SkillName.Focus, 50}, }, new Dictionary<MagieType, int>() {})); 
				Classe.RegisterClasse(new Classe(15, "Juge Eternel",2,4,false,false, new List<int>(){}, new Dictionary<SkillName, double>() { {SkillName.Anatomy, 85}, {SkillName.AnimalLore, 30}, {SkillName.Camping, 30}, {SkillName.Parry, 80}, {SkillName.Peacemaking, 30}, {SkillName.Discordance, 30}, {SkillName.EvalInt, 30}, {SkillName.Healing, 60}, {SkillName.Herding, 50}, {SkillName.Hiding, 30}, {SkillName.Provocation, 30}, {SkillName.Lockpicking, 30}, {SkillName.Magery, 100}, {SkillName.Equitation, 50}, {SkillName.Tactics, 85}, {SkillName.Snooping, 30}, {SkillName.Musicianship, 30}, {SkillName.Poisoning, 30}, {SkillName.Archery, 50}, {SkillName.Stealing, 30}, {SkillName.AnimalTaming, 30}, {SkillName.Tracking, 30}, {SkillName.Veterinary, 30}, {SkillName.Swords, 100}, {SkillName.Macing, 100}, {SkillName.Fencing, 100}, {SkillName.Wrestling, 100}, {SkillName.Meditation, 30}, {SkillName.Focus, 50}, }, new Dictionary<MagieType, int>() {})); 
				Classe.RegisterClasse(new Classe(16, "Chef de guerre",2,4,false,false, new List<int>(){}, new Dictionary<SkillName, double>() { {SkillName.Anatomy, 85}, {SkillName.AnimalLore, 30}, {SkillName.Camping, 30}, {SkillName.Parry, 80}, {SkillName.Peacemaking, 30}, {SkillName.Discordance, 30}, {SkillName.EvalInt, 30}, {SkillName.Healing, 60}, {SkillName.Herding, 50}, {SkillName.Hiding, 30}, {SkillName.Provocation, 30}, {SkillName.Lockpicking, 30}, {SkillName.Magery, 100}, {SkillName.Equitation, 50}, {SkillName.Tactics, 85}, {SkillName.Snooping, 30}, {SkillName.Musicianship, 30}, {SkillName.Poisoning, 30}, {SkillName.Archery, 50}, {SkillName.Stealing, 30}, {SkillName.AnimalTaming, 30}, {SkillName.Tracking, 30}, {SkillName.Veterinary, 30}, {SkillName.Swords, 100}, {SkillName.Macing, 100}, {SkillName.Fencing, 100}, {SkillName.Wrestling, 100}, {SkillName.Meditation, 30}, {SkillName.Focus, 50}, }, new Dictionary<MagieType, int>() {})); 
				Classe.RegisterClasse(new Classe(17, "Trouble-Fête",2,4,false,false, new List<int>(){}, new Dictionary<SkillName, double>() { {SkillName.Anatomy, 85}, {SkillName.AnimalLore, 30}, {SkillName.Camping, 30}, {SkillName.Parry, 80}, {SkillName.Peacemaking, 30}, {SkillName.Discordance, 30}, {SkillName.EvalInt, 30}, {SkillName.Healing, 60}, {SkillName.Herding, 50}, {SkillName.Hiding, 30}, {SkillName.Provocation, 30}, {SkillName.Lockpicking, 30}, {SkillName.Magery, 100}, {SkillName.Equitation, 50}, {SkillName.Tactics, 85}, {SkillName.Snooping, 30}, {SkillName.Musicianship, 30}, {SkillName.Poisoning, 30}, {SkillName.Archery, 50}, {SkillName.Stealing, 30}, {SkillName.AnimalTaming, 30}, {SkillName.Tracking, 30}, {SkillName.Veterinary, 30}, {SkillName.Swords, 100}, {SkillName.Macing, 100}, {SkillName.Fencing, 100}, {SkillName.Wrestling, 100}, {SkillName.Meditation, 30}, {SkillName.Focus, 50}, }, new Dictionary<MagieType, int>() {})); 
				Classe.RegisterClasse(new Classe(18, "Tireur Elite",2,4,false,false, new List<int>(){}, new Dictionary<SkillName, double>() { {SkillName.Anatomy, 100}, {SkillName.AnimalLore, 30}, {SkillName.Camping, 30}, {SkillName.Parry, 60}, {SkillName.Peacemaking, 30}, {SkillName.Discordance, 30}, {SkillName.EvalInt, 30}, {SkillName.Healing, 60}, {SkillName.Herding, 50}, {SkillName.Hiding, 50}, {SkillName.Provocation, 30}, {SkillName.Lockpicking, 30}, {SkillName.Magery, 30}, {SkillName.Equitation, 50}, {SkillName.Tactics, 100}, {SkillName.Snooping, 30}, {SkillName.Musicianship, 30}, {SkillName.Poisoning, 50}, {SkillName.Archery, 100}, {SkillName.Stealing, 30}, {SkillName.AnimalTaming, 30}, {SkillName.Tracking, 60}, {SkillName.Veterinary, 30}, {SkillName.Swords, 60}, {SkillName.Macing, 60}, {SkillName.Fencing, 60}, {SkillName.Wrestling, 60}, {SkillName.Meditation, 50}, {SkillName.Focus, 100}, }, new Dictionary<MagieType, int>() {})); 
				Classe.RegisterClasse(new Classe(19, "Archer Equestre",2,3,false,false, new List<int>(){}, new Dictionary<SkillName, double>() { {SkillName.Anatomy, 85}, {SkillName.AnimalLore, 30}, {SkillName.Camping, 30}, {SkillName.Parry, 60}, {SkillName.Peacemaking, 30}, {SkillName.Discordance, 30}, {SkillName.EvalInt, 30}, {SkillName.Healing, 60}, {SkillName.Herding, 50}, {SkillName.Hiding, 50}, {SkillName.Provocation, 30}, {SkillName.Lockpicking, 30}, {SkillName.Magery, 30}, {SkillName.Equitation, 100}, {SkillName.Tactics, 85}, {SkillName.Snooping, 30}, {SkillName.Musicianship, 30}, {SkillName.Poisoning, 50}, {SkillName.Archery, 100}, {SkillName.Stealing, 30}, {SkillName.AnimalTaming, 30}, {SkillName.Tracking, 60}, {SkillName.Veterinary, 30}, {SkillName.Swords, 60}, {SkillName.Macing, 60}, {SkillName.Fencing, 60}, {SkillName.Wrestling, 60}, {SkillName.Meditation, 50}, {SkillName.Focus, 60}, }, new Dictionary<MagieType, int>() {})); 
				Classe.RegisterClasse(new Classe(20, "Chasseur de prime",2,4,false,false, new List<int>(){}, new Dictionary<SkillName, double>() { {SkillName.Anatomy, 85}, {SkillName.AnimalLore, 30}, {SkillName.Camping, 30}, {SkillName.Parry, 60}, {SkillName.Peacemaking, 30}, {SkillName.Discordance, 30}, {SkillName.EvalInt, 30}, {SkillName.Healing, 60}, {SkillName.Herding, 50}, {SkillName.Hiding, 50}, {SkillName.Provocation, 30}, {SkillName.Lockpicking, 30}, {SkillName.Magery, 30}, {SkillName.Equitation, 50}, {SkillName.Tactics, 85}, {SkillName.Snooping, 30}, {SkillName.Musicianship, 30}, {SkillName.Poisoning, 100}, {SkillName.Archery, 100}, {SkillName.Stealing, 30}, {SkillName.AnimalTaming, 30}, {SkillName.Tracking, 100}, {SkillName.Veterinary, 30}, {SkillName.Swords, 60}, {SkillName.Macing, 60}, {SkillName.Fencing, 60}, {SkillName.Wrestling, 60}, {SkillName.Meditation, 50}, {SkillName.Focus, 60}, }, new Dictionary<MagieType, int>() {})); 
				Classe.RegisterClasse(new Classe(21, "Tireur Arcanique",2,3,false,false, new List<int>(){}, new Dictionary<SkillName, double>() { {SkillName.Anatomy, 85}, {SkillName.AnimalLore, 30}, {SkillName.Camping, 30}, {SkillName.Parry, 60}, {SkillName.Peacemaking, 30}, {SkillName.Discordance, 30}, {SkillName.EvalInt, 30}, {SkillName.Healing, 60}, {SkillName.Herding, 50}, {SkillName.Hiding, 50}, {SkillName.Provocation, 30}, {SkillName.Lockpicking, 30}, {SkillName.Magery, 100}, {SkillName.Equitation, 50}, {SkillName.Tactics, 85}, {SkillName.Snooping, 30}, {SkillName.Musicianship, 30}, {SkillName.Poisoning, 50}, {SkillName.Archery, 100}, {SkillName.Stealing, 30}, {SkillName.AnimalTaming, 30}, {SkillName.Tracking, 60}, {SkillName.Veterinary, 30}, {SkillName.Swords, 60}, {SkillName.Macing, 60}, {SkillName.Fencing, 60}, {SkillName.Wrestling, 60}, {SkillName.Meditation, 50}, {SkillName.Focus, 60}, }, new Dictionary<MagieType, int>() {})); 
				Classe.RegisterClasse(new Classe(22, "Fleche Devoue",2,3,false,false, new List<int>(){}, new Dictionary<SkillName, double>() { {SkillName.Anatomy, 85}, {SkillName.AnimalLore, 30}, {SkillName.Camping, 30}, {SkillName.Parry, 60}, {SkillName.Peacemaking, 30}, {SkillName.Discordance, 30}, {SkillName.EvalInt, 30}, {SkillName.Healing, 60}, {SkillName.Herding, 50}, {SkillName.Hiding, 50}, {SkillName.Provocation, 30}, {SkillName.Lockpicking, 30}, {SkillName.Magery, 100}, {SkillName.Equitation, 50}, {SkillName.Tactics, 85}, {SkillName.Snooping, 30}, {SkillName.Musicianship, 30}, {SkillName.Poisoning, 50}, {SkillName.Archery, 100}, {SkillName.Stealing, 30}, {SkillName.AnimalTaming, 30}, {SkillName.Tracking, 60}, {SkillName.Veterinary, 30}, {SkillName.Swords, 60}, {SkillName.Macing, 60}, {SkillName.Fencing, 60}, {SkillName.Wrestling, 60}, {SkillName.Meditation, 50}, {SkillName.Focus, 60}, }, new Dictionary<MagieType, int>() {})); 
				Classe.RegisterClasse(new Classe(23, "Predateur Nocturne",2,3,false,false, new List<int>(){}, new Dictionary<SkillName, double>() { {SkillName.Anatomy, 85}, {SkillName.AnimalLore, 30}, {SkillName.Camping, 30}, {SkillName.Parry, 60}, {SkillName.Peacemaking, 30}, {SkillName.Discordance, 30}, {SkillName.EvalInt, 30}, {SkillName.Healing, 60}, {SkillName.Herding, 50}, {SkillName.Hiding, 50}, {SkillName.Provocation, 30}, {SkillName.Lockpicking, 30}, {SkillName.Magery, 100}, {SkillName.Equitation, 50}, {SkillName.Tactics, 85}, {SkillName.Snooping, 30}, {SkillName.Musicianship, 30}, {SkillName.Poisoning, 50}, {SkillName.Archery, 100}, {SkillName.Stealing, 30}, {SkillName.AnimalTaming, 30}, {SkillName.Tracking, 60}, {SkillName.Veterinary, 30}, {SkillName.Swords, 60}, {SkillName.Macing, 60}, {SkillName.Fencing, 60}, {SkillName.Wrestling, 60}, {SkillName.Meditation, 50}, {SkillName.Focus, 60}, }, new Dictionary<MagieType, int>() {})); 
				Classe.RegisterClasse(new Classe(24, "Vent et terre",2,3,false,false, new List<int>(){}, new Dictionary<SkillName, double>() { {SkillName.Anatomy, 85}, {SkillName.AnimalLore, 30}, {SkillName.Camping, 30}, {SkillName.Parry, 60}, {SkillName.Peacemaking, 30}, {SkillName.Discordance, 30}, {SkillName.EvalInt, 30}, {SkillName.Healing, 60}, {SkillName.Herding, 50}, {SkillName.Hiding, 50}, {SkillName.Provocation, 30}, {SkillName.Lockpicking, 30}, {SkillName.Magery, 100}, {SkillName.Equitation, 50}, {SkillName.Tactics, 85}, {SkillName.Snooping, 30}, {SkillName.Musicianship, 30}, {SkillName.Poisoning, 50}, {SkillName.Archery, 100}, {SkillName.Stealing, 30}, {SkillName.AnimalTaming, 30}, {SkillName.Tracking, 60}, {SkillName.Veterinary, 30}, {SkillName.Swords, 60}, {SkillName.Macing, 60}, {SkillName.Fencing, 60}, {SkillName.Wrestling, 60}, {SkillName.Meditation, 50}, {SkillName.Focus, 60}, }, new Dictionary<MagieType, int>() {})); 
				Classe.RegisterClasse(new Classe(25, "Justicier",2,3,false,false, new List<int>(){}, new Dictionary<SkillName, double>() { {SkillName.Anatomy, 85}, {SkillName.AnimalLore, 30}, {SkillName.Camping, 30}, {SkillName.Parry, 60}, {SkillName.Peacemaking, 30}, {SkillName.Discordance, 30}, {SkillName.EvalInt, 30}, {SkillName.Healing, 60}, {SkillName.Herding, 50}, {SkillName.Hiding, 50}, {SkillName.Provocation, 30}, {SkillName.Lockpicking, 30}, {SkillName.Magery, 100}, {SkillName.Equitation, 50}, {SkillName.Tactics, 85}, {SkillName.Snooping, 30}, {SkillName.Musicianship, 30}, {SkillName.Poisoning, 50}, {SkillName.Archery, 100}, {SkillName.Stealing, 30}, {SkillName.AnimalTaming, 30}, {SkillName.Tracking, 60}, {SkillName.Veterinary, 30}, {SkillName.Swords, 60}, {SkillName.Macing, 60}, {SkillName.Fencing, 60}, {SkillName.Wrestling, 60}, {SkillName.Meditation, 50}, {SkillName.Focus, 60}, }, new Dictionary<MagieType, int>() {})); 
				Classe.RegisterClasse(new Classe(26, "Cibleur Voile",2,3,false,false, new List<int>(){}, new Dictionary<SkillName, double>() { {SkillName.Anatomy, 85}, {SkillName.AnimalLore, 30}, {SkillName.Camping, 30}, {SkillName.Parry, 60}, {SkillName.Peacemaking, 30}, {SkillName.Discordance, 30}, {SkillName.EvalInt, 30}, {SkillName.Healing, 60}, {SkillName.Herding, 50}, {SkillName.Hiding, 50}, {SkillName.Provocation, 30}, {SkillName.Lockpicking, 30}, {SkillName.Magery, 100}, {SkillName.Equitation, 50}, {SkillName.Tactics, 85}, {SkillName.Snooping, 30}, {SkillName.Musicianship, 30}, {SkillName.Poisoning, 50}, {SkillName.Archery, 100}, {SkillName.Stealing, 30}, {SkillName.AnimalTaming, 30}, {SkillName.Tracking, 60}, {SkillName.Veterinary, 30}, {SkillName.Swords, 60}, {SkillName.Macing, 60}, {SkillName.Fencing, 60}, {SkillName.Wrestling, 60}, {SkillName.Meditation, 50}, {SkillName.Focus, 60}, }, new Dictionary<MagieType, int>() {})); 



		/*				Classe.RegisterClasse(new Classe(1, "Forgeron",new Dictionary<SkillName, double>() 
						{  
							{SkillName.Blacksmith, 100},
							{SkillName.Mining, 100},
							{SkillName.ArmsLore, 100}
						}));
*/
				}
		}
}
